# Generated by Django 6.0 on 2025-12-09 05:49

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dish_meal_alter_dish_user_alter_dish_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Масса (г)'),
        ),
        migrations.AddIndex(
            model_name='dailygoal',
            index=models.Index(fields=['user', 'date'], name='daily_goals_user_id_b20e89_idx'),
        ),
        migrations.AddIndex(
            model_name='dailygoal',
            index=models.Index(fields=['-date'], name='daily_goals_date_208e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['user', '-created_at'], name='dishes_user_id_1c1064_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['meal'], name='dishes_meal_id_6a644e_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['name'], name='dishes_name_a4005d_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'date', 'meal_type'], name='meals_user_id_839a10_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['-date'], name='meals_date_90429e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='payments_created_26b056_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='subscriptio_end_dat_763002_idx'),
        ),
    ]
