# Generated by Django 6.0 on 2025-12-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dish_weight_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_user_id_1b771c_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_transac_a1f824_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_created_26b056_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_user_id_8d58fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_end_dat_763002_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
